repos:
  -
    repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      -
        id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-sfs
        # SFS101: String literal formatting using percent operator.
        # SFS201: String literal formatting using .format method.
        # SFS301: String literal formatting using f-string.
        args: [--max-line-length=120, --extend-ignore=SFS3 D107 D100 D104 D401 D412 SFS101 SFS201]

  -
    repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      -
        id: isort

  -
    repo: local
    hooks:
      -
        id: docs
        name: docs
        entry: /bin/bash gen_docs.sh
        language: system
        pass_filenames: false
        always_run: true
