name: pypi-publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  trial-by-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check for changes in the package
        id: check-changes
        run: |
          files_changed=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")
          changes_in_folder=false
          for file in $files_changed; do
            if [[ $file == "thronetrader/"* && $file != "thronetrader/__init__.py" && $file != "thronetrader/requirements.txt" ]]; then
              changes_in_folder=true
              break
            fi
          done
          echo "Changes: ${files_changed}"
          if [[ "${{ env.changes_in_folder }}" == 'true' ]]; then
            echo "Changes identified in package. Running pytest."
          else
            echo "No changes were found in package. Skipping pytest."
          fi
          echo "changes_in_folder=$changes_in_folder" >> $GITHUB_ENV

      - name: Install dependencies and run functional tests
        if: env.changes_in_folder == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r thronetrader/requirements.txt
      - name: Run pytest
        if: env.changes_in_folder == 'true'
        run: |
          python -m pytest tests/

  vanguard:
    needs: trial-by-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install build twine
      - name: Create packages
        run: |
          python -m build
          twine check dist/*

  coronation:
    if: github.event_name == 'release'
    needs: vanguard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Upload to pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install build twine
          twine upload dist/*.whl
