name: pypi-publish

on:
  push:
  release:
    types: [published]

jobs:
  trial-by-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r thronetrader/requirements.txt
          python -m pytest tests/

  vanguard:
    needs: trial-by-pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install build twine
      - name: Create packages
        run: |
          python -m build
          twine check dist/*

  coronation:
    if: github.event_name == 'release'
    needs: vanguard
    runs-on: ubuntu-latest
    steps:
      - name: Upload to pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*.whl
